# Generated by Django 5.2.7 on 2025-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_options_remove_document_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Manual progress override 0-100', verbose_name='Progress (%)'),
        ),
    ]
