# Generated by Django 5.2.7 on 2025-11-13 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_type', models.CharField(choices=[('act7', 'Act 7 - Level Approval'), ('act14', 'Act 14 - Structure Acceptance'), ('act15', 'Act 15 - Final Acceptance')], max_length=10, verbose_name='Act Type')),
                ('act_number', models.CharField(blank=True, max_length=50, verbose_name='Act Number')),
                ('act_date', models.DateField(verbose_name='Act Date')),
                ('representative_builder', models.CharField(max_length=200, verbose_name='Builder Representative')),
                ('representative_supervision', models.CharField(max_length=200, verbose_name='Supervision Representative')),
                ('representative_designer', models.CharField(max_length=200, verbose_name='Designer Representative')),
                ('level_from', models.CharField(blank=True, max_length=50, verbose_name='Level From')),
                ('level_to', models.CharField(blank=True, max_length=50, verbose_name='Level To')),
                ('work_description', models.TextField(blank=True, verbose_name='Work Description')),
                ('concrete_class', models.CharField(blank=True, max_length=50, verbose_name='Concrete Class')),
                ('concrete_work', models.CharField(blank=True, max_length=200, verbose_name='Concrete Work')),
                ('referenced_acts', models.TextField(blank=True, verbose_name='Referenced Acts')),
                ('quality_protocols', models.TextField(blank=True, verbose_name='Quality Protocols')),
                ('conclusion_text', models.TextField(blank=True, verbose_name='Conclusion')),
                ('all_designers', models.TextField(blank=True, verbose_name='All Designers')),
                ('all_supervision', models.TextField(blank=True, verbose_name='All Supervision')),
                ('referenced_documents', models.TextField(blank=True, verbose_name='Referenced Documents')),
                ('findings_permits', models.TextField(blank=True, verbose_name='Findings - Permits')),
                ('findings_execution', models.TextField(blank=True, verbose_name='Findings - Execution')),
                ('findings_site', models.TextField(blank=True, verbose_name='Findings - Site')),
                ('decision_text', models.TextField(blank=True, verbose_name='Decision')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='acts/%Y/%m/%d/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='acts/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_acts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='core.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Act',
                'verbose_name_plural': 'Acts',
                'ordering': ['-act_date', '-created_at'],
            },
        ),
    ]
