# Generated by Django 5.2.8 on 2025-11-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_act7_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linked_documents',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.document', verbose_name='Linked Documents'),
        ),
    ]
