# Generated by Django 5.2.8 on 2025-11-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_linked_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes for employees', verbose_name='Notes'),
        ),
    ]
