# Generated by Django 5.2.8 on 2025-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('privileged', 'Privileged User'), ('admin', 'Admin')], default='privileged', max_length=20, verbose_name='Role'),
        ),
    ]
