# Generated by Django 5.2.8 on 2025-12-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_push_subscription'),
        ('core', '0012_alter_userprofile_role'),
    ]

    operations = [
    ]
