# Generated by Django 5.2.8 on 2026-01-04 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20251218_0928'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('document_generated', 'Document Generated'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('act_created', 'Act Created'), ('act_updated', 'Act Updated'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('user_created', 'User Created'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], max_length=50, verbose_name='Action Type')),
                ('description', models.CharField(help_text='Human-readable description of the action', max_length=500, verbose_name='Description')),
                ('content_type', models.CharField(blank=True, help_text='Type of related object (project, document, etc.)', max_length=50, verbose_name='Related Model')),
                ('object_id', models.IntegerField(blank=True, help_text='ID of the related object', null=True, verbose_name='Object ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data about the action', verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx'), models.Index(fields=['action_type', '-created_at'], name='core_activi_action__0be70f_idx')],
            },
        ),
    ]
