# Generated by Django 5.2.8 on 2026-01-04 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('act7', 'Act 7'), ('act14', 'Act 14'), ('act15', 'Act 15'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('report', 'Report'), ('other', 'Other')], max_length=50, verbose_name='Template Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_content', models.JSONField(default=dict, help_text='JSON object with default field values', verbose_name='Default Content')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='Template File')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_budget', models.DecimalField(decimal_places=2, help_text='Total planned budget in BGN', max_digits=12, verbose_name='Initial Budget')),
                ('currency', models.CharField(default='BGN', max_length=3, verbose_name='Currency')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Budget',
                'verbose_name_plural': 'Project Budgets',
            },
        ),
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('materials', 'Materials'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('permits', 'Permits & Licenses'), ('subcontractors', 'Subcontractors'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=50, verbose_name='Category')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Invoice Number')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Vendor/Supplier')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_expenses', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.projectbudget')),
            ],
            options={
                'verbose_name': 'Budget Expense',
                'verbose_name_plural': 'Budget Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.CharField(choices=[('location', 'Location Descriptions'), ('work_type', 'Work Types'), ('materials', 'Materials'), ('legal', 'Legal Clauses'), ('safety', 'Safety Notes'), ('quality', 'Quality Standards'), ('other', 'Other')], max_length=50, verbose_name='Category')),
                ('content', models.TextField(verbose_name='Content')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for searching', max_length=255, verbose_name='Tags')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Snippet',
                'verbose_name_plural': 'Text Snippets',
                'ordering': ['-usage_count', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('task_due', 'Task Due Soon'), ('act_pending', 'Act Pending Approval'), ('project_deadline', 'Project Deadline'), ('document_expiry', 'Document Expiring'), ('budget_alert', 'Budget Alert'), ('custom', 'Custom Reminder')], max_length=50, verbose_name='Reminder Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('trigger_date', models.DateTimeField(verbose_name='Trigger Date')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.task')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['trigger_date'],
                'indexes': [models.Index(fields=['status', 'trigger_date'], name='core_remind_status_460c3b_idx'), models.Index(fields=['recipient', '-trigger_date'], name='core_remind_recipie_3f143c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Min Temperature (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Max Temperature (°C)')),
                ('condition', models.CharField(blank=True, help_text='e.g., Sunny, Rainy, Cloudy, Snowy', max_length=100, verbose_name='Weather Condition')),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Precipitation (mm)')),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Wind Speed (km/h)')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('work_stopped', models.BooleanField(default=False, help_text='Whether work was stopped due to weather', verbose_name='Work Stopped')),
                ('impact_notes', models.TextField(blank=True, help_text='Description of weather impact on work', verbose_name='Impact Notes')),
                ('api_source', models.CharField(blank=True, help_text='API source if automatically fetched', max_length=100, verbose_name='Data Source')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Raw API Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to='core.project')),
            ],
            options={
                'verbose_name': 'Weather Log',
                'verbose_name_plural': 'Weather Logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['project', '-date'], name='core_weathe_project_6d0d0a_idx')],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
