# Generated by Django 5.2.8 on 2026-01-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_documenttemplate_projectbudget_budgetexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accessible_projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this client can access', related_name='client_users', to='core.project'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client - View Own Projects Only'), ('privileged', 'Privileged User'), ('admin', 'Admin')], default='privileged', max_length=20, verbose_name='Role'),
        ),
    ]
