# Generated by Django 5.2.8 on 2026-01-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_accessible_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='endpoint_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(max_length=2000),
        ),
    ]
