# Generated by Django 5.2.8 on 2026-01-05 08:41

import hashlib
from django.db import migrations


def populate_endpoint_hash(apps, schema_editor):
    PushSubscription = apps.get_model('core', 'PushSubscription')
    for sub in PushSubscription.objects.all():
        if sub.endpoint and not sub.endpoint_hash:
            sub.endpoint_hash = hashlib.sha256(sub.endpoint.encode()).hexdigest()
            sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pushsubscription_endpoint_hash_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_endpoint_hash),
    ]
