# Generated by Django 5.2.8 on 2026-01-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_populate_endpoint_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetexpense',
            unique_together={('budget', 'date')},
        ),
    ]
