# Generated by Django 5.2.8 on 2026-01-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_task_assigned_to_name_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpense',
            name='expense_currency',
            field=models.CharField(choices=[('BGN', 'BGN'), ('EUR', 'EUR')], default='BGN', max_length=3, verbose_name='Currency'),
        ),
    ]
