# Generated by Django 5.2.8 on 2026-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_budgetexpense_expense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetexpense',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
