# Generated by Django 5.2.8 on 2026-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accessible_projects',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('privileged', 'Privileged User'), ('admin', 'Admin')], default='privileged', max_length=20, verbose_name='Role'),
        ),
    ]
