# Generated by Django 5.2.8 on 2026-01-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_budgetexpense_unique_together'),
        ('core', '0024_remove_userprofile_accessible_projects_and_more'),
    ]

    operations = [
    ]
